language: go
sudo: false

install: true
before_script: echo "Don't run pre-build"
script: echo "Don't build"
after_script: echo "Don't run post build"

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    bucket: $AWS_DIY_WEB_BUCKET
    skip_cleanup: true
    acl: public_read
    on:
        branch: master
