sudo: false

install: true
script: echo "ETate says: Nothing to build"

deploy: provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    bucket: $AWS_DIY_WEB_BUCKET
    skip_cleanup: true
    acl: public_read
    on:
        branch: master
